# relativeURLs = true
# Change the default theme to be use when building the site with Hugo
baseURL = "https://hieu192.github.io/workshop2-12-2025"
relativeURLs = true
canonifyURLs = true
theme = "hugo-theme-learn"

# Ignore warnings
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = "https://github.com/Hieu192/workshop2-12-2025/edit/main/content/"
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Video Analysis with Amazon Bedrock and OpenSearch"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://aws.amazon.com/blogs"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.vi]
title = "Phân tích Video với Amazon Bedrock và OpenSearch"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

